[package]
name = "wca_scorecards"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]
# name = "wca_scorecards"
# crate-type = ["cdylib"]

[dependencies]
wca_scorecards_lib = { git = "https://github.com/Daniel-Anker-Hermansen/WCA_tools_lib" }
#wca_scorecards_lib = { path = "../WCA_tools_lib/wca_scorecards_lib"}

# [dependencies.pyo3]
# version = "0.16.4"
# features = ["extension-module"]
